Wow, to bad you've died. You forgot to refuel after your last mission
in 1 episode. That's very very bad. There are a lot of fun levels ahead
you must see them, so I'm giving you a chance to continue your quest.
Ofcourse not for free. You must complete my tasks and then may be I'll
let you go from this DUNGEON level. Well, if you're ready then press ESC.

